ITW/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: xuezaigds@gmail.com
# @Last Modified time: 2016-09-19 23:06:09
from datetime import datetime
from flask import current_app
from . import db

""" 用户管理模块 """


class Users(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    random_id = db.Column(db.String(10), nullable=False)
    cname = db.Column(db.String(50))
    ename = db.Column(db.String(50), nullable=False)
    title = db.Column(db.String(50), nullable=False)
    country = db.Column(db.String(128), nullable=False, default='中国')
    pid = db.Column(db.String(20), nullable=False, default='None')
    affiliation = db.Column(db.String(128), nullable=False)
    edas1 = db.Column(db.String(256))
    edas2 = db.Column(db.String(256))
    edas3 = db.Column(db.String(256))
    receipt = db.Column(db.String(10))
    receipt_title = db.Column(db.String(128))
    receipt_id = db.Column(db.String(50))
    email = db.Column(db.String(50), nullable=False)
    vip_num = db.Column(db.String(50))
    reg_type = db.Column(db.String(128), nullable=False)
    tutorial = db.Column(db.String(10), nullable=False)
    tutorial_item = db.Column(db.String(128))
    need_invite = db.Column(db.String(10), nullable=False)
    excursion = db.Column(db.String(128), nullable=False)
    gender = db.Column(db.String(10))
    birthday = db.Column(db.String(50))
    food_preference = db.Column(db.String(50), nullable=False)
    goto_talk = db.Column(db.String(10), nullable=False)

    total_fee = db.Column(db.Integer, nullable=False)
    

class Reservations(db.Model):
    __tablename__ = 'reservations'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    affiliation = db.Column(db.String(128), nullable=False)
    checkin_date = db.Column(db.String(50), nullable=False)
    checkout_date = db.Column(db.String(50), nullable=False)
    identity_num = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), nullable=False)
    room_type = db.Column(db.String(50), nullable=False)
    

class Rooms(db.Model):
    __tablename__ = 'rooms'
    id = db.Column(db.Integer, primary_key=True)
    type_num = db.Column(db.Integer, nullable=False)
    type_name = db.Column(db.String(50), nullable=False)
    total_num = db.Column(db.Integer, nullable=False)
    available_num = db.Column(db.Integer, nullable=False)
    price = db.Column(db.Integer, nullable=False)
    in_date = db.Column(db.Integer, nullable=False)

ITW/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config

db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)

    # Register all the filter.
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .travel import travel as travel_blueprint
    app.register_blueprint(travel_blueprint)
    from .program import program as program_blueprint
    app.register_blueprint(program_blueprint, url_prefix='/program')
    from .registration import registration as registration_blueprint
    app.register_blueprint(registration_blueprint, url_prefix='/registration')
    from .accommodation import accommodation as accommodation_blueprint
    app.register_blueprint(accommodation_blueprint, url_prefix='/accommodation')

    return app

ITW/accommodation/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
accommodation = Blueprint('accommodation', __name__)
from . import views

ITW/accommodation/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from . import accommodation
from flask import render_template, jsonify, request
from ..models import Reservations, Rooms
from ..util.send_email import send_email
from .. import db
import sys
import time, random, string


@accommodation.route('/')
def index():
    return render_template("accommodation/main.html", tab='accommodation', tag='index')


@accommodation.route('/reservation', methods=['GET', 'POST'])
def reservation():
    if request.method == 'GET':
        type1 = Rooms.query.filter_by(type_num=1, in_date=24).first()
        type2 = Rooms.query.filter_by(type_num=2, in_date=24).first()
        type3 = Rooms.query.filter_by(type_num=3, in_date=24).first()
        type4 = Rooms.query.filter_by(type_num=4, in_date=24).first()
        type5 = Rooms.query.filter_by(type_num=5, in_date=24).first()
        type6 = Rooms.query.filter_by(type_num=6, in_date=24).first()
        if type1:
            num1 = type1.available_num
        else:
            num1 = 0
        if type2:
            num2 = type2.available_num
        else:
            num2 = 0
        if type3:
            num3 = type3.available_num
        else:
            num3 = 0
        if type4:
            num4 = type4.available_num
        else:
            num4 = 0
        if type5:
            num5 = type5.available_num
        else:
            num5 = 0
        if type6:
            num6 = type6.available_num
        else:
            num6 = 0
        print num1,num2,num3,num4,num5,num6
        return render_template("accommodation/main.html",
                                tab='accommodation',
                                tag='reservation',
                                num1=num1,
                                num2=num2,
                                num3=num3,
                                num4=num4,
                                num5=num5,
                                num6=num6)
    elif request.method =='POST':
        if request.form.get('op') == 'get_num':
            in_date = request.form.get('in_date')
            in_date = int(in_date) + 24
            type1 = Rooms.query.filter(Rooms.type_num==1, Rooms.in_date<=in_date).all()
            type2 = Rooms.query.filter(Rooms.type_num==2, Rooms.in_date<=in_date).all()
            type3 = Rooms.query.filter(Rooms.type_num==3, Rooms.in_date<=in_date).all()
            type4 = Rooms.query.filter(Rooms.type_num==4, Rooms.in_date<=in_date).all()
            type5 = Rooms.query.filter(Rooms.type_num==5, Rooms.in_date<=in_date).all()
            type6 = Rooms.query.filter(Rooms.type_num==6, Rooms.in_date<=in_date).all()
            num1 = 0
            num2 = 0
            num3 = 0
            num4 = 0
            num5 = 0
            num6 = 0
            for room in type1:
                num1 = num1 + room.available_num
            for room in type2:
                num2 = num2 + room.available_num
            for room in type3:
                num3 = num3 + room.available_num
            for room in type4:
                num4 = num4 + room.available_num
            for room in type5:
                num5 = num5 + room.available_num
            for room in type6:
                num6 = num6 + room.available_num
            return jsonify(status='success',
                            num1=num1,
                            num2=num2,
                            num3=num3,
                            num4=num4,
                            num5=num5,
                            num6=num6)
        else:
            date_dict = {
                '0':'11/24',
                '1':'11/25',
                '2':'11/26',
                '3':'11/27',
                '4':'11/28',
                '5':'11/29',
                '6':'11/30',
                '7':'12/01'
            }
            room_dict = {
                1: 'City View Room(One Queen bed)',
                2: 'City View Room(Two Single beds)',
                3: 'River View Room(One Queen bed)',
                4: 'River View Room(Two Single beds)',
                5: 'Bisuness Suit',
                6: 'River View Suit',
            }
            name = request.form.get('name')
            affiliation = request.form.get('affiliation')
            in_date_num = request.form.get('in-date')
            in_date = date_dict[in_date_num]
            out_date = request.form.get('out-date')
            uid = request.form.get('uid')
            email = request.form.get('email')
            room_type = request.form.get('room-type')
            # print name,affiliation,in_date,out_date,uid,email,room_type
            if room_type == '2' or room_type == '5':
                curr_room = Rooms.query.filter_by(type_num=room_type, in_date=24).first_or_404()
                if curr_room.available_num > 0:
                    curr_room.available_num = curr_room.available_num - 1
                else:
                    curr_room = Rooms.query.filter_by(type_num=room_type, in_date=25).first_or_404()
                    if curr_room.available_num > 0:
                        curr_room.available_num = curr_room.available_num - 1
                    else:
                        return jsonify(status='no rooms')
            elif room_type == '6':
                if int(in_date_num) < 2: 
                    curr_room = Rooms.query.filter_by(type_num=room_type, in_date=24).first_or_404()
                    if curr_room.available_num > 0:
                        curr_room.available_num = curr_room.available_num - 1
                    else:
                        return jsonify(status='no rooms')
                else:
                    curr_room = Rooms.query.filter_by(type_num=room_type, in_date=24).first_or_404()
                    if curr_room.available_num > 0:
                        curr_room.available_num = curr_room.available_num - 1
                    curr_room = Rooms.query.filter_by(type_num=room_type, in_date=26).first_or_404()
                    if curr_room.available_num > 0:
                        curr_room.available_num = curr_room.available_num - 1
                    else:
                        return jsonify(status='no rooms')
            elif room_type == '1':
                curr_room = Rooms.query.filter_by(type_num=room_type).first_or_404()
                if curr_room.available_num > 0:
                    curr_room.available_num = curr_room.available_num - 1
                else:
                    return jsonify(status='no rooms')
            else:
                if int(in_date_num) == 0: 
                    return jsonify(status='no rooms')
                curr_room = Rooms.query.filter_by(type_num=room_type).first_or_404()
                if curr_room.available_num > 0:
                    curr_room.available_num = curr_room.available_num - 1
                else:
                    return jsonify(status='no rooms')
            
            curr_reservation = Reservations(name=name,
                                            affiliation=affiliation,
                                            checkin_date=in_date,
                                            checkout_date=out_date,
                                            identity_num=uid,
                                            email=email,
                                            room_type=room_dict[curr_room.type_num])
            template = u'<p style="font-size: 20px;font-weight: 600">Reserved Successfully!</p>\
						<p>Your name id：' + str(name) + u'</p>\
						<p>Your check-in date：' + str(in_date) + u'</p>\
						<p>Your check-out date：' + str(out_date) + u'</p>\
						<p>Your room type is：' + str(room_dict[curr_room.type_num]) + u'</p>\
						<p>The price is: ￥' + str(curr_room.price) + u' / day</p><hr>\
                        <p><strong>Note:</strong> The listed price contains only one breakfast. You can pay for the extra breakfast at check-in if needed.</p>\
                        <p>Sent by ITW2018 Organizing Committee</p>'
            subject = 'ITW2018-Reservation Successfully'
            ret = send_email(email, name, template, subject)
            if ret:
                db.session.add(curr_reservation)
                db.session.commit()
                return jsonify(status='success',
                                name=name,
                                in_date=in_date,
                                out_date=out_date,
                                room_type=room_dict[curr_room.type_num],
                                price=curr_room.price)
            else:
                return jsonify(status='failed')

ITW/main/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
main = Blueprint('main', __name__)
from . import views

ITW/main/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from . import main
from flask import render_template, jsonify, request


@main.route('/')
def index():
    return render_template("main/main.html", tab="home")


@main.route('/committee')
def committee():
    return render_template("main/main.html", tab='committee')


@main.route('/papers')
def papers():
    return render_template("main/main.html", tab='papers')


@main.route('/venue')
def venue():
    return render_template("main/main.html", tab='venue')


@main.route('/show_driver')
def show_driver():
    return render_template("venue/show_driver.html")


@main.route('/CITW')
def citw():
    return render_template("main/main.html", tab="citw")

ITW/program/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
program = Blueprint('program', __name__)
from . import views

ITW/program/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from . import program
from flask import render_template, jsonify, request


@program.route('/glance')
def glance():
    return render_template("program/main.html",
                           tab="program",
                           tag="glance")


@program.route('/full_program')
def full_program():
    return render_template("program/main.html",
                           tab="program",
                           tag="full_program")


@program.route('/invited_papers')
def invited_papers():
    return render_template("program/main.html",
                           tab="program",
                           tag="invited_papers")


@program.route('/tutorial_call')
def tutorial_call():
    return render_template("program/main.html",
                           tab="program",
                           tag="tutorial_call")


@program.route('/social_events')
def social_events():
    return render_template("program/main.html",
                           tab="program",
                           tag="social_events")


@program.route('/plenary_talks')
def plenary_talks():
    return render_template("program/main.html",
                           tab="program",
                           tag="plenary_talks")

ITW/travel/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint
travel = Blueprint('travel', __name__)
from . import views

ITW/travel/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from . import travel
from flask import render_template, jsonify, request


@travel.route('/travel/about_GuangZhou')
def index():
    return render_template("travel/main.html",
                           tab="travel",
                           tag="guangzhou")


@travel.route('/travel/about_SYSU')
def sysu():
        return render_template("travel/main.html",
                               tab="travel",
                               tag='sysu')


@travel.route('/travel/Visa_Information')
def visa():
        return render_template("travel/main.html",
                               tab="travel",
                               tag='visa')


@travel.route('/travel/Hong_Kong')
def hongkong():
        return render_template("travel/main.html",
                               tab="travel",
                               tag='hongkong')

ITW/util/__init__.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

# Register all the filter.
from . import send_email

ITW/templates/alert_modal.html
<div class="modal center" id="modal-alert" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-alert">
        <button class="close modal-alert" data-dismiss="modal">&times;</button>
        <div class="modal-content modal-alert">
            <div class="modal-body"></div>
        </div>
    </div>
</div>

ITW/templates/base.html
<!DOCTYPE html>

<html>
<head>
    {% include 'header.html' %}
    <title>{% block title %}{% endblock %}</title>
    {% block header_ext %}{% endblock %}
</head>


<body>
{% include 'navbar.html' %}
<div class="content-wrap">
    <!-- content in this page -->
    {% block content %}{% endblock %}
</div>

{% include 'alert_modal.html' %}
{% include 'submit-comfirm.html' %}
{% include 'footer.html' %}
<!-- <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.min.js"></script> -->
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% block footer_ext %}{% endblock %}

</body>
</html>

ITW/templates/footer.html
<!-- 赞助商logo -->
<div id="page-footer-container" class="container" style="background-color: #FFFFFF;margin-bottom: 20px;">
    <div id="sponser-content" class="row">
      <section id="sponsers">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-4 sponser-img">
              <a href="https://www.ieee.org/index.html" target="_blank"><img src="{{ url_for('static',filename='images/IEEE.png') }}" alt="IEEE"></a>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-4 sponser-img">
              <a href="http://www.itsoc.org/" target="_blank"><img src="{{ url_for('static',filename='images/IT.png') }}" alt="IT"></a>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-4 sponser-img">
              <a href="http://www.sysu.edu.cn" target="_blank"><img src="{{ url_for('static',filename='images/SYSU.jpg') }}" alt="SYSU"></a>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-4 sponser-img">
              <a href="http://www.swjtu.edu.cn/" target="_blank"><img src="{{ url_for('static',filename='images/XJU.jpg') }}" alt="XJU"></a>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-4 sponser-img">
              <a href="http://www.dgut.edu.cn/" target="_blank"><img src="{{ url_for('static',filename='images/DG.jpg') }}" alt="DG"></a>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-4 sponser-img">
              <a href="http://www.huawei.com/cn/" target="_blank"><img src="{{ url_for('static',filename='images/HUAWEI.png') }}" alt="HUAWEI"></a>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-4 sponser-img">
              <a href="http://www.ieccr.net/cieit/index.asp" target="_blank"><img src="{{ url_for('static',filename='images/ITS.jpg') }}" alt="ITS"></a>
            </div>
        </div>
      </section>
    </div>
</div>

<!-- 网页尾部 -->
<footer>
  <div class="copyright">
      <div class="container">
          <i class="fa fa-copyright"></i>2018 - ITW2018. All rights reserved <br>
          ITW2018 Organizing Committee<br>
          Contact Us : itw2018gz@gmail.com <br>
     </div>
  </div>
</footer>

ITW/templates/header.html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1">
<meta name="renderer" content="webkit">
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">

<!-- title在具体模板中设置 -->
<!-- <title>ITW-2018</title> -->

<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

<link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" type="text/css">

<script src="{{ url_for('static', filename='js/jquery-3.1.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

ITW/templates/navbar.html
<!-- 固定导航栏 -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="{% if tab == 'home' %}active{% endif %}">
          <a href="{{ url_for('main.index') }}" class="content-tab level-1">Home</a>
        </li>

        <li class="dropdown{% if tab == 'program' %} active{% endif %}" onmouseover="show_sub_menu('#sub-menu1');" onmouseout="hide_sub_menu('#sub-menu1');">
          <a href="#" class="content-tab level-1" aria-haspopup="true" aria-expanded="false">Program
            <span>
              <i class="fa fa-sm fa-caret-down" style="font-size: 14px"></i>
            </span>
          </a>
          <ul id="sub-menu1" class="dropdown-menu">
            <li>
              <a href="{{ url_for('program.glance') }}" class="content-tab level-2">At a Glance</a>
            </li>
            <li>
              <a href="{{ url_for('program.full_program') }}" class="content-tab level-2">Full Program</a>
            </li>
            <li>
              <a href="{{ url_for('program.plenary_talks') }}" class="content-tab level-2">Plenary Talks</a>
            </li>
            <li>
              <a href="{{ url_for('program.invited_papers') }}" class="content-tab level-2">Invited Papers</a>
            </li>
            <li>
              <a href="{{ url_for('program.tutorial_call') }}" class="content-tab level-2">Tutorials</a>
            </li>
            <li>
              <a href="{{ url_for('program.social_events') }}" class="content-tab level-2">Social Events</a>
            </li>
          </ul>
        </li>

        <li class="{% if tab == 'committee' %}active{% endif %}">
          <a href="{{ url_for('main.committee') }}" class="content-tab level-1">Committee</a>
        </li>

        <li class="{% if tab == 'papers' %}active{% endif %}">
          <a href="{{ url_for('main.papers') }}" class="content-tab level-1">CFP</a>
        </li>

        <li class="{% if tab == 'registration' %}active{% endif %}" onmouseover="show_sub_menu('#sub-menu2');" onmouseout="hide_sub_menu('#sub-menu2');">
          <a href="#" class="content-tab level-1" aria-haspopup="true" aria-expanded="false">Registration
            <span>
              <i class="fa fa-sm fa-caret-down" style="font-size: 14px"></i>
            </span>
            <ul id="sub-menu2" class="dropdown-menu">
              <li>
                <a href="{{ url_for('registration.registrations') }}" class="content-tab level-2">Registration</a>
              </li>
              <li>
                <a href="{{ url_for('registration.student_travel_grant') }}" class="content-tab level-2">Student Travel Grant</a>
              </li>
            </ul>
          </a>
        </li>

        <li class="{% if tab == 'venue' %}active{% endif %}">
          <a href="{{ url_for('main.venue') }}" class="content-tab level-1">Venue</a>
        </li>

        <li class="{% if tab == 'accommodation' %}active{% endif %}">
          <a href="{{ url_for('accommodation.index') }}" class="content-tab level-1">Accommodation</a>
        </li>

        <li class="dropdown{% if tab == 'travel' %} active{% endif %}" onmouseover="show_sub_menu('#sub-menu6');" onmouseout="hide_sub_menu('#sub-menu6');">
          <a href="{{ url_for('travel.index') }}" class="content-tab level-1" aria-haspopup="true" aria-expanded="false">Travel
            <span>
              <i class="fa fa-sm fa-caret-down" style="font-size: 14px"></i>
            </span>
          </a>
          <ul id="sub-menu6" class="dropdown-menu">
            <li>
              <a href="{{ url_for('travel.index') }}" class="content-tab level-2">About Guangzhou</a>
            </li>
            <li>
              <a href="{{ url_for('travel.sysu') }}" class="content-tab level-2">About SYSU</a>
            </li>
            <li>
              <a href="{{ url_for('travel.visa') }}" class="content-tab level-2">Visa Information</a>
            </li>
            <li>
              <a href="{{ url_for('travel.hongkong') }}" class="content-tab level-2">Guangzhou ←→ Hong Kong</a>
            </li>
          </ul>
        </li>

        <li class="{% if tab == 'citw' %}active{% endif %}">
          <a href="{{ url_for('main.citw') }}" class="content-tab level-1">SYSU-CITW</a>
        </li>
      </ul>
    </div>

    {# 手机端显示 #}
    <div id="navbar" class="navbar-mobile visible-xs">
      <div class="dropdown" style="display: inline-block">
        <a href="#" data-toggle="dropdown" class="navbar-more dropdown-toggle">
          <i class="fa fa-align-justify"></i>
        </a>
        <ul class="dropdown-menu">
          <li class="{% if tab == 'home' %}active{% endif %}">
            <a href="{{ url_for('main.index') }}" class="content-tab level-1">Home</a>
          </li>

          <li class="dropdown{% if tab == 'program' %} active{% endif %}" onmouseover="show_sub_menu('#sub-menu1');" onmouseout="hide_sub_menu('#sub-menu1');">
            <a href="#" class="content-tab level-1" aria-haspopup="true" aria-expanded="false">Program
              <span>
                <i class="fa fa-sm fa-caret-down" style="font-size: 14px"></i>
              </span>
            </a>
            <ul id="sub-menu1" class="sub-menu">
              <li>
                <a href="{{ url_for('program.glance') }}" class="content-tab level-2">At a Glance</a>
              </li>
              <li>
                <a href="{{ url_for('program.full_program') }}" class="content-tab level-2">Full Program</a>
              </li>
              <li>
                <a href="{{ url_for('program.plenary_talks') }}" class="content-tab level-2">Plenary Talks</a>
              </li>
              <li>
                <a href="{{ url_for('program.invited_papers') }}" class="content-tab level-2">Invited Papers</a>
              </li>
              <li>
                <a href="{{ url_for('program.tutorial_call') }}" class="content-tab level-2">Tutorials</a>
              </li>
              <li>
                <a href="{{ url_for('program.social_events') }}" class="content-tab level-2">Social Events</a>
              </li>
            </ul>
          </li>

          <li class="{% if tab == 'committee' %}active{% endif %}">
            <a href="{{ url_for('main.committee') }}" class="content-tab level-1">Committee</a>
          </li>

          <li class="{% if tab == 'papers' %}active{% endif %}">
            <a href="{{ url_for('main.papers') }}" class="content-tab level-1">CFP</a>
          </li>

          <li class="{% if tab == 'registration' %}active{% endif %}" onmouseover="show_sub_menu('#sub-menu2');" onmouseout="hide_sub_menu('#sub-menu2');">
            <a href="#" class="content-tab level-1" aria-haspopup="true" aria-expanded="false">Registration
              <span>
                <i class="fa fa-sm fa-caret-down" style="font-size: 14px"></i>
              </span>
              <ul id="sub-menu2" class="dropdown-menu">
                <li>
                  <a href="{{ url_for('registration.registrations') }}" class="content-tab level-2">Registration</a>
                </li>
                <li>
                  <a href="{{ url_for('registration.student_travel_grant') }}" class="content-tab level-2">Student Travel Grant</a>
                </li>
              </ul>
            </a>
          </li>

          <li class="{% if tab == 'venue' %}active{% endif %}">
            <a href="{{ url_for('main.venue') }}" class="content-tab level-1">Venue</a>
          </li>

          <li class="{% if tab == 'accommodation' %}active{% endif %}">
            <a href="{{ url_for('accommodation.index') }}" class="content-tab level-1">Accommodation</a>
          </li>

          <li class="dropdown{% if tab == 'travel' %} active{% endif %}" onmouseover="show_sub_menu('#sub-menu6');" onmouseout="hide_sub_menu('#sub-menu6');">
            <a href="{{ url_for('travel.index') }}" class="content-tab level-1" aria-haspopup="true" aria-expanded="false">Travel
              <span>
                <i class="fa fa-sm fa-caret-down" style="font-size: 14px"></i>
              </span>
            </a>
            <ul id="sub-menu6" class="sub-menu">
              <li>
                <a href="{{ url_for('travel.index') }}" class="content-tab level-2">About Guangzhou</a>
              </li>
              <li>
                <a href="{{ url_for('travel.sysu') }}" class="content-tab level-2">About SYSU</a>
              </li>
              <li>
                <a href="{{ url_for('travel.visa') }}" class="content-tab level-2">Visa Information</a>
              </li>
              <li>
                <a href="{{ url_for('travel.hongkong') }}" class="content-tab level-2">Guangzhou ←→ Hong Kong</a>
              </li>
            </ul>
          </li>

          <li class="{% if tab == 'citw' %}active{% endif %}">
            <a href="{{ url_for('main.citw') }}" class="content-tab level-1">SYSU-CITW</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>


<div class="container" style="margin-top: 60px;">
  <!-- 轮播图 -->
  <div class="row">
    <img src="{{ url_for('static',filename='images/main.jpg') }}" style="width: 100%;">
  </div>
</div>

ITW/templates/submit-comfirm.html
<div class="modal fade" id="submit-comfirm-modal" tabindex="-1" role="dialog" aria-labelledby="myComfirmLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myComfirmLabel">Comfirm</h4>
            </div>
            <div class="modal-body" style="height: 100px;font-size: medium">
                <div class="inline-cntent">
                    <span id="total-fee-before"></span>
                    <span id="total-fee"></span>
                    <span id="total-fee-after"></span>
                </div>
                <div>
                    <span id="next-line-content"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">close</button>
                <button id="user-submit-comfirm" type="button" class="btn btn-primary">submit</button>
            </div>
        </div>
    </div>
</div>